version: "3.1"

services:

  db:
    restart: always
    image: postgres
    container_name: livLife #you can change this
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=livLifeAdmin
      - POSTGRES_PASS=Admin@123
      - POSTGRES_DB=RedLeaf
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
      image: dpage/pgadmin4
      container_name: livLife #you can change this
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: root
      restart: always


volumes:
  postgres_data:
