# Generated by Django 3.2.5 on 2021-12-22 09:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('from_place', models.CharField(max_length=300)),
                ('to_place', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='packages/images')),
                ('price', models.CharField(max_length=15)),
                ('accomodation', models.IntegerField(default=5)),
                ('no_of_days', models.IntegerField()),
                ('no_of_nights', models.IntegerField(default=5)),
                ('transportation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=None, size=None)),
                ('food_facilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=None, size=None)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('reviews', models.CharField(max_length=500, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='order_package',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='', max_length=300)),
                ('package_uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('package_date', models.CharField(max_length=11)),
                ('adults', models.IntegerField()),
                ('childrens', models.IntegerField()),
                ('paid_amount', models.CharField(default='200', max_length=50)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='packeges.package')),
            ],
        ),
    ]
