# Generated by Django 3.2.5 on 2021-11-30 02:32

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='packages/images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('accomodation', models.IntegerField(default=5)),
                ('no_of_days', models.IntegerField()),
                ('transportation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=None, size=None)),
                ('food_facilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=None, size=None)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('reviews', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='packageOrder',
            fields=[
                ('order_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('package_uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('package_date', models.CharField(max_length=11)),
                ('adults', models.IntegerField()),
                ('childrens', models.IntegerField()),
            ],
        ),
    ]
