# Generated by Django 3.2.3 on 2021-11-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('no_of_days', models.IntegerField()),
                ('transportation', models.CharField(max_length=1000)),
                ('food_facilities', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('reviews', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
    ]
