# Generated by Django 3.2.3 on 2021-11-17 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packeges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='package',
            name='rating',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')]),
        ),
    ]
