# Generated by Django 3.2.3 on 2021-11-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packeges', '0002_auto_20211117_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
