# Generated by Django 3.2.3 on 2021-11-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packeges', '0003_alter_package_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
