# Generated by Django 3.2.3 on 2021-11-18 10:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packeges', '0006_alter_package_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='food_facilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=None, size=None),
        ),
        migrations.AlterField(
            model_name='package',
            name='transportation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=None, size=None),
        ),
    ]
