# Generated by Django 3.2.3 on 2021-11-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packeges', '0009_auto_20211126_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='accomodation',
            field=models.IntegerField(default=5),
        ),
    ]
