# Generated by Django 3.2.3 on 2021-12-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packeges', '0011_alter_packageorder_contact_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='name',
            new_name='from_place',
        ),
        migrations.AddField(
            model_name='package',
            name='no_of_nights',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='package',
            name='to_place',
            field=models.CharField(default='india', max_length=300),
        ),
    ]
