# Generated by Django 3.2.3 on 2021-12-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packeges', '0012_auto_20211206_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='to_place',
            field=models.CharField(max_length=300),
        ),
    ]
