# Generated by Django 3.2.3 on 2021-12-12 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packeges', '0013_alter_package_to_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageorder',
            name='paid_amount',
            field=models.CharField(default='200', max_length=50),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
