# Generated by Django 3.2.3 on 2021-12-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packeges', '0014_auto_20211212_1738'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='packageorder',
            name='order_id',
            field=models.CharField(max_length=300),
        ),
    ]
