# Generated by Django 3.2.3 on 2021-12-12 13:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packeges', '0017_alter_packageorder_package_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageorder',
            name='package_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
