# Generated by Django 3.2.3 on 2021-12-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packeges', '0018_alter_packageorder_package_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageorder',
            name='order_id',
            field=models.CharField(default='dfjh', max_length=300, primary_key=True, serialize=False),
        ),
    ]
