# Generated by Django 3.2.3 on 2021-12-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packeges', '0019_alter_packageorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageorder',
            name='order_id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
