# Generated by Django 3.2.3 on 2021-12-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packeges', '0020_alter_packageorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageorder',
            name='name',
            field=models.CharField(default='aman', max_length=50),
        ),
    ]
