# Generated by Django 3.2.5 on 2021-12-22 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flightOrder',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('book_id', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 12, 22, 9, 22, 11, 967970, tzinfo=utc))),
            ],
        ),
    ]
