# Generated by Django 3.2.5 on 2021-11-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
