# Generated by Django 3.2.3 on 2021-11-28 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
