# Generated by Django 3.2.3 on 2021-11-28 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_clientreview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreview',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
